### ISSUE TITLE
PlantMod tree settings are bugged

### ISSUE THREAD

**Issue by jkluch** [aedenthorn/ValheimMods#15]
In here you're checking if name contains `"tree"`
https://github.com/aedenthorn/ValheimMods/blob/e58b03f854dd3baf36e8e463cf3f359a8f6448f8/PlantMod/BepInExPlugin.cs#L180-L188
In my game this wasn't triggering and everything was using `growthTimeMultPlant` I think because when you plant a tree it makes a sapling.  So `"tree"` should probably be `"sapling"` but I haven't verified.

Also I had a more general question, do you know why the multiplier doesn't see to be working as I'd expect?
Default grow time with a 1.0 multiplier shows something like `0/4200` on hover
Grow time with a .2 multiplier which should be around `0/840` ends up really being something like `0/180`

**Comment by aedenthorn** [comment]
Thanks, can you try the new version on nexus and see if it works now?

**Comment by jkluch** [comment]
Looks good, thanks.
