### ISSUE TITLE
Unequipped item dropped if inventory is full

### ISSUE THREAD

**Issue by creativegaffers** [aedenthorn/ValheimMods#45]
If your inventory is full and you equip an item like a Dverger Circlet, the item it is replacing will be dropped instead of placed in the inventory slot the new item used to occupy.  This is annoying when you are standing around in your base, but it's a royal pain in the ass when you're sailing across the ocean since the item is effectively gone.  I even knew about this issue and still managed to do it like an idiot.  Hopefully there's something that can be done about it.  The other equipment mod doesn't seem to have this issue, but yours is so much better at recovering gear from tombstones, so I much prefer it.

**Comment by aedenthorn** [comment]
what mod?

**Comment by creativegaffers** [comment]
Sorry, it's the Extended Player Inventory mod.

**Comment by aedenthorn** [comment]
please try the new version

**Comment by creativegaffers** [comment]
Seems to work great, thanks much.
