### ISSUE TITLE
License

### ISSUE THREAD

**Issue by swedneck** [aedenthorn/ValheimMods#5]
Hi, if you want people to be able to use and modify your code you should add a license to this repo, see https://choosealicense.com/

**Comment by aedenthorn** [comment]
I don't believe in licenses... I would never sue someone for what they do with my code, but you'll have to take my word for it... sorry!

**Comment by swedneck** [comment]
I take this as you not wanting anyone to use this software then, that's a shame.

**Comment by Ragnarok700** [comment]
I'll leave this comment here: in most jurisdictions, if you do not add an explicit licence normal copyright laws apply by default. This is obviously really bad for code shared publicly and completed to deal with.

If your goal is really to share freely without restrictions, use something like the MIT licence. If you want people to be force to shared their source, go for GNU GPL v3.

Choosing "no licence" means you are effectively opting for the "default one", which is not super pleasant for external contributors... And you've done so much good work so it'd be a shame for it to become problematic to use, share and contribute to in the future! :)

**Comment by aedenthorn** [comment]
Take it as you will! I don't believe in copyright, so no, I'm not choosing the default license, and no I have no desire to restrict anyone's use of my work.

**Comment by Ragnarok700** [comment]
Ah, I see. Well, maybe you can simply put a comment somewhere (maybe in the README or a LICENCE file) saying "_This entire repository's contents are released into the public domain._" or something along those lines? :) Then it will truly be free and unrestricted forever (for the most part)! Not quite as good as a proper freeing type of licence, but it is certainly better than nothing being mentioned at all.

I take you at your word (i.e.: "I have no desire to restrict anyone's use of my work") and will still contribute as I can regardless but I still think you may want to at least mention you released it to public domain somewhere in the repo.

**Comment by aedenthorn** [comment]
That's a good idea, thank you.
