### ISSUE TITLE
False positive on container sizes with new black metal chest

### ISSUE THREAD

**Issue by robclancy** [aedenthorn/ValheimMods#54]
This line will be true for the new chest, and most likely reduce its size: https://github.com/aedenthorn/ValheimMods/blob/master/CustomContainerSizes/BepInExPlugin.cs#L119

I had the same issue on my mod, you can see my fix in here https://github.com/robclancy/valheim-bigger-chests/issues/4.

I'm not going to add configuration to my mod so when people request it I direct them to yours and was just checking if you had the same bug I did.

**Comment by aedenthorn** [comment]
Thanks, please try the new version
