### ISSUE TITLE
BepInEx requirements (reference)

### ISSUE THREAD

**Issue by Ragnarok700** [aedenthorn/ValheimMods#7]
It seems all the projects expect the referenced dlls to be in "..\..\BepInEx\". The way the current repo is setup, these files are in "..\BepInEx\".
I see two simple solutions:
1. Move all folders into a sub-folder, therefore respecting the expected path by the projects.
2. Modify each project files to point to "..\BepInEx\" instead for those dlls.

I personally think solution # 2 would be the best solution so as to not change the structure of the folders/repo. I propose doing it myself using a regex over the project files to quickly fix this. Will you accept a pull request for this if I fix it?

**Comment by aedenthorn** [comment]
I don't understand the problem... thats where the dll files are on my machine

**Comment by Ragnarok700** [comment]
Please allow me to provide more details:
1) Here's the folder of a fresh clone I just made. As you can see, like in the latest commit of the repo (master branch), the **BepInEx** folder is in the same location as all the projects and the VS solution file.
![image](https://user-images.githubusercontent.com/821781/110210925-20f8c080-7e62-11eb-854c-943e5a460595.png)
2) Once you open the solution in **VS2017** and try to compile some of the projects, you get an error concerning references. The first one I tried was **TimeMod** (I love taking short breaks to play a bit, but don't want to start/close the game every time :P ). When I try to build this project I get a few errors (missing references). Other projects produce errors too. If I try to build the full solution I get 409 errors. I figure you may have the **BepInEx** folder (and other references) twice so it is trying to reference outside your local repo (but still using a relative path). See below:
![image](https://user-images.githubusercontent.com/821781/110211247-bb0d3880-7e63-11eb-8725-33b4e141b18b.png)
![image](https://user-images.githubusercontent.com/821781/110211281-f27be500-7e63-11eb-8961-bfbd83c104a5.png)
3) With a quick look at the project file itself in a text editor you can see that the references to the **BepInEx** folder are two levels up instead of one (like the other references):
![image](https://user-images.githubusercontent.com/821781/110211380-54d4e580-7e64-11eb-96bf-04163938ba6d.png)

So, my proposal is this:
I'll make a quick commit that basically just updates those relative paths (i.e.: remove one "..\" so that it targets the **BepInEx** folder that is inside the repo). The goal here is to make it easier for others to compile without having to move the **BepInEx** folder around (which is what I originally did) to allow compilation.

**Comment by Ragnarok700** [comment]
Oh, it should also be mentioned that some of them do point to the right place already, like **AnimationSpeed**:
![image](https://user-images.githubusercontent.com/821781/110211681-be092880-7e65-11eb-89bd-b64a6c96180e.png)

**Comment by Ragnarok700** [comment]
After applying the fix I was still left with 11 errors over a few projects. I quickly realized some of the projects referenced the physic module improperly too so I'll throw that in too since it is a similar issue. See image below for one project:
![image](https://user-images.githubusercontent.com/821781/110212047-7d121380-7e67-11eb-8590-4ab32321cab2.png)

**Comment by Ragnarok700** [comment]
After those three rel path fixes across the projects all compiled properly except one, CustomMeshes, due to the missing reference to AssimpNet (v5.0.0.0):
![image](https://user-images.githubusercontent.com/821781/110212331-e21a3900-7e68-11eb-8bd9-5b96f6840078.png)
Not sure how you want to handle that one (add it to the repo and fix the relative path) or add a readme with info concerning this lib to be downloaded by the devs on their machine. Therefore, I won't place this in the pr for the rel path fix for this issue.
