### ISSUE TITLE
[BUG] Mistland update

### ISSUE THREAD

**Issue by Vodianoi** [aedenthorn/ValheimMods#77]
```
[Error  : Unity Log] MissingMethodException: bool Player.IsItemQueued(ItemDrop/ItemData)
Stack trace:
ExtendedPlayerInventory.QuickAccessBar.Update () (at <4c0568a64cd44a31b6fcb2184a5e5942>:0)
```
ExtendedPlayerInventory v0.3.4 (r2modmanager)
When loading world (running on Dedicated Server) Mistland update

**Comment by Vodianoi** [comment]
Not showing when building from source, missing push to thunderstore?

**Comment by aedenthorn** [comment]
I don't upload my mods anywhere but Nexus Mods. Nexus Mods rewards mod authors when people download their mods from there.
