### ISSUE TITLE
[CraftFromContainers] Update existing version on thunderstore.io

### ISSUE THREAD

**Issue by lokvahdin** [aedenthorn/ValheimMods#78]
For those of us who are not using Nexus Mods we are stuck on ver 2.2.4 of Craft from containers.

**Comment by aedenthorn** [comment]
Nexus Mods rewards mod authors, I only upload my mods there.

**Comment by lokvahdin** [comment]
That sucks, I only use thunderstore.io because the mods don't work when using vortex.
