### ISSUE TITLE
Missing copyDll.bat

### ISSUE THREAD

**Issue by Ragnarok700** [aedenthorn/ValheimMods#8]
Where can we find a copy of copyDll.bat ?

**Comment by aedenthorn** [comment]
It's just a batch file to copy the dll into the plugins folder and add it to a zip file, you can create your own, just replace the x's with the paths

copy xxxxxxxxxxxx\ValheimMods\%1\bin\Debug\%1.dll xxxxxxxxxxxx\Valheim\BepInEx\Plugins\
"C:\Program Files\7-Zip\7z.exe" a xxxxxxxxxxxx\Valheim\BepInEx\Plugins\%1.zip xxxxxxxxxxxx\Valheim\BepInEx\Plugins\%1.dll

**Comment by Ragnarok700** [comment]
Thanks for the info. This is exactly what I assumed but figured I'd ask anyway just in case! :)
