### ISSUE TITLE
Safe Zone - MissingMethodException (bug)

### ISSUE THREAD

**Issue by luxzg** [aedenthorn/ValheimMods#81]
Forum post:
https://forums.nexusmods.com/index.php?/topic/10623843-safe-zone/?p=119341798

Nexus bug post:
https://www.nexusmods.com/valheim/mods/1582?tab=bugs

Error in Unity log:
[Error  : Unity Log] MissingMethodException: StatusEffect SEMan.AddStatusEffect(StatusEffect,bool)
Stack trace:

Details:
As someone correctly noticed, it's the Safe Zone mod that spams the log with this error.
I'm less interested in status effect, more interested in not seeing this in the log... and whatever else may be happening because of it :)

If we could get an updated, I'd be grateful.

Original bug founder also added a request for hotkey to disable status effect.

Thanks!

**Comment by aedenthorn** [comment]
Why are you posting this here? I didn't make that mod.
