### ISSUE TITLE
[Compass Suggestion] Option to completely disable map pin tracking on the compass? (Just a compass)

### ISSUE THREAD

**Issue by Hiomapaperi** [aedenthorn/ValheimMods#92]
Hi there,

Any chance of a compass option that is JUST the cardinal direction element?  Or even just the player tracking?

The compass you've made unfortunately creates performance issues, even when the radius is set to a max of say (2), when there are many map pins on a server; The performance issues are similar in-line with zooming out on the mini-map or the big map, even with the radius reduced.

Thanks for your consideration!

/h

**Comment by aedenthorn** [comment]
please try the new version

**Comment by Hiomapaperi** [comment]
> 

I'll definitely try it out when it's on Thunderstore! (I'm not familiar with compiling from source, c#, etc.)
It's appreciated!

/h

**Comment by aedenthorn** [comment]
it's on Nexus Mods
